Repository AY2324S2-CS2103T-W11-3/tp, pull requests merged in 2024-04, with the labels that each got.

#126 Update some native funtionalities and add new View Command
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddProfCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddProfCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CancelCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/booking/Booking.java
  src/main/java/seedu/address/model/booking/UniqueBookingList.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandListPanel.java
  src/main/resources/fonts/Source Pro/SourceCodePro-Medium.ttf
  src/main/resources/fonts/Source Pro/SourceCodePro-Regular.ttf
  src/main/resources/images/AlexYeoh.png
  src/main/resources/images/BerniceYu.png
  src/main/resources/images/CharlotteOliveiro.png
  src/main/resources/images/DaDuke.png
  src/main/resources/images/DavidLi.png
  src/main/resources/images/address_icon2.svg
  src/main/resources/images/default_image.png
  src/main/resources/images/endtime_icon.png
  src/main/resources/images/notes_icon.png
  src/main/resources/images/time_icon.png
  src/main/resources/view/BookingListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/stylesheets/DarkTheme.css
  src/main/resources/view/stylesheets/LightTheme.css
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BookCommandTest.java
  src/test/java/seedu/address/logic/commands/CancelCommandTest.java
Labels: enhancement, priority.High

#127 Update user guide with relevant info and images
  docs/UserGuide.md
  docs/images/BookingCard.png
  docs/images/ContactCard.png
  docs/images/HelpWindow.png
  docs/images/MainPanel.png
  docs/images/ResultBox_Error.png
  docs/images/ResultBox_Success.png
  docs/images/Ui.png
  docs/images/UserGuideApp.png
  docs/images/UserGuideFront.png
  docs/index.md
Labels: documentation, priority.Medium

#132 User guide improvements
  docs/UserGuide.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/professors/data.json
Labels: documentation

#136 Fix ProfCommand bug
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/parser/AddProfCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonProfDataStorage.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: bug

#138 Add test cases for ProfCommand and its parser
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/test/java/seedu/address/logic/commands/ProfCommandTest.java
  src/test/java/seedu/address/logic/parser/ProfCommandParserTest.java
Labels: test

#140 Complete booking section of UG
  docs/UserGuide.md
  docs/images/UserGuideApp.png
  docs/images/UserGuideFront.png
Labels: documentation

#196 Fix UG formatting issues
  docs/UserGuide.md
Labels: bug, documentation

#197 Fix Documentation issues regarding User Guide
  docs/UserGuide.md
  docs/images/SampleUi.png
Labels: documentation, priority.Medium

#198 Fix booking date bugs
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/parser/BookCommandParser.java
  src/main/java/seedu/address/model/booking/Booking.java
  src/main/java/seedu/address/model/booking/EndTime.java
  src/main/java/seedu/address/model/booking/StartTime.java
  src/test/java/seedu/address/logic/parser/BookCommandParserTest.java
  src/test/java/seedu/address/model/booking/EndTimeTest.java
  src/test/java/seedu/address/model/booking/StartTimeTest.java
  src/test/java/seedu/address/testutil/TypicalBookings.java
Labels: bug, priority.Medium

#199 Change how ui gets image path
  src/main/java/seedu/address/model/person/ImagePath.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: bug, priority.High

#202 Fix few other related issues in UG
  copyright.txt
  docs/UserGuide.md
  docs/images/commandBox.png
  docs/team/gauravuj.md
  src/main/java/seedu/address/model/person/ImagePath.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/images/clock.png
  src/main/resources/images/code_icon.png
  src/main/resources/images/default_image.png
  src/main/resources/images/michaeldavid.png
  src/main/resources/images/sethlewisgilbert.png
Labels: documentation, priority.Medium

#201 Fix various messages and documentation bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: bug, documentation, priority.High

#206 Fixes editing related bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: bug

#212 [docs]: Add more images to commands
  docs/UserGuide.md
  docs/images/AliasCommandSuccess.png
  docs/images/CancelAllCommandSuccess.png
  docs/images/SearchCommandError.png
  docs/images/SearchCommandSampleBookings.png
  docs/images/SearchCommandSuccess.png
  docs/images/ViewCommandSuccess.png
Labels: documentation, priority.Medium

#216 [bug]: Fix caret issues in Command Box
  src/main/java/seedu/address/ui/CommandBox.java
Labels: bug

#218 [bug]: Fix pasting issues in Command Box
  src/main/java/seedu/address/ui/CommandBox.java
Labels: bug
