Repository AY2324S2-CS2103T-W11-3/tp, pull requests merged in 2024-03, with the labels that each got.

#72 Improve UI and add Booking List Card and Panel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/BookingCard.java
  src/main/java/seedu/address/ui/BookingListPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookingListCard.fxml
  src/main/resources/view/BookingListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/styleSheets/DarkTheme.css
Labels: user interface

#86 Fix app crash when no datafile/folder
  src/main/java/seedu/address/MainApp.java
Labels: bug, priority.High

#88 User Guide Update: Command Summary and Introduction
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/styleSheets/DarkTheme.css
Labels: documentation, priority.Medium

#83 Update ModelClass UML diagram to reflect new codebase
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation, priority.High

#90 Add Theme command to change themes
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Theme.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/styleSheets/DarkTheme.css
  src/main/resources/view/styleSheets/LightTheme.css
Labels: type.Feature, priority.Low

#93 Update UML diagram for Ui Component
  docs/diagrams/UiClassDiagram.puml
Labels: documentation, priority.High

#96 Documentation improvements
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/booking/Booking.java
Labels: documentation, priority.Medium

#102 Introduce CommandList Panel and Enhance UI with Modern Scrollbars
  docs/images/NewUi.png
  src/main/java/seedu/address/model/command/CommandInfo.java
  src/main/java/seedu/address/model/person/ImagePath.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/TerminalWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_icon.png
  src/main/resources/images/booking_icon.png
  src/main/resources/images/code_icon.png
  src/main/resources/images/default_image_2.png
  src/main/resources/images/email_icon.png
  src/main/resources/images/person_icon.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/terminal_icon.png
  src/main/resources/view/CommandListPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TerminalWindow.fxml
  src/main/resources/view/stylesheets/CommandListPanel.css
  src/main/resources/view/stylesheets/DarkTheme.css
  src/main/resources/view/stylesheets/Extensions.css
  src/main/resources/view/stylesheets/HelpWindow.css
  src/main/resources/view/stylesheets/LightTheme.css
Labels: enhancement, user interface, priority.High

#109 Improve documentation
  docs/UserGuide.md
  src/main/java/seedu/address/ui/.TerminalWindow.java.icloud
Labels: documentation

#113 Fix theme parsing bug
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Theme.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: bug, priority.Low

#114 Move CommandListPanel to HelpWindow to optimize focus
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookingListCard.fxml
  src/main/resources/view/BookingListPanel.fxml
  src/main/resources/view/CommandListPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/stylesheets/CommandListPanel.css
  src/main/resources/view/stylesheets/DarkTheme.css
  src/main/resources/view/stylesheets/Extensions.css
  src/main/resources/view/stylesheets/HelpWindow.css
  src/main/resources/view/stylesheets/LightTheme.css
Labels: enhancement, priority.Medium

#116 Add DG guide to theme switching
  docs/DeveloperGuide.md
  docs/diagrams/ThemeModelSequenceDiagram.puml
  docs/images/ThemeModelSequenceDiagram.png
Labels: documentation

#119 Add notes section for bookings
  build.gradle
  src/main/java/seedu/address/logic/commands/AddAliasCommand.java
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/parser/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/booking/Booking.java
  src/main/java/seedu/address/model/booking/Notes.java
  src/main/java/seedu/address/storage/JsonAdaptedBooking.java
  src/main/java/seedu/address/ui/BookingCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookingListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/BookCommandParserTest.java
  src/test/java/seedu/address/model/booking/NotesTest.java
  src/test/java/seedu/address/testutil/BookingBuilder.java
Labels: enhancement

#120 Add diagrams to document BookCommand
  docs/DeveloperGuide.md
  docs/diagrams/BookCommandActivityDiagram.puml
  docs/diagrams/BookCommandSequenceDiagram.puml
  docs/images/BookCommandActivityDiagram.png
  docs/images/BookCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation
